data_path: data/labeling_merged_algae_7class_v2_geo
output_dir: outputs/labeling_merged_algae_7class_v2
run_name: merged_algae7_seed42
epochs: 100
batch_size: 4
val_batch_size: 4
num_workers: 4
prefetch_factor: 1
lr: 0.00004
encoder_lr: 0.000001
weight_decay: 0.02
scheduler_type: PolynomialLR
scheduler_kwargs: '{"power": 0.9}'
warmup_iters: 200
grad_clip_norm: 35.0
grad_accum_steps: 3
num_classes: 7
input_channels: 9
source_tiles: true
segmentation_taxonomy: merged_algae_7class
tile_size: 768
class_sampling_prob: 0.5
class_sampling_mode: global
val_group_metrics: true
seed: 42
device: cuda
flip_prob: 0.5
backbone_loader: hf
hf_dinov3_model_name_or_path: facebook/dinov3-vitl16-pretrain-lvd1689m
hf_local_files_only: true
mask2former_pretrained_model_name_or_path: facebook/mask2former-swin-large-ade-semantic
disable_mask2former_pretrained: false
freeze_backbone: false
hidden_dim: 256
classification_loss_type: ce
early_stopping_patience: 4
val_interval: 5
early_stopping_min_delta: 0.0001
max_best_checkpoints: 1
fusion_type: input
