data_path: data/labeling_semseg_11cls_multispectral
output_dir: outputs
run_name: labeling_data_11cls_multispectral_ce_teacher
epochs: 100
batch_size: 12
val_batch_size: 4
num_workers: 8
prefetch_factor: 1
lr: 0.00004
encoder_lr: 0.000001
weight_decay: 0.02
scheduler_type: PolynomialLR
scheduler_kwargs: '{"power": 0.9}'
warmup_iters: 200
grad_clip_norm: 35.0
grad_accum_steps: 1
resize_width: 768
resize_height: 768
input_channels: 6
num_classes: 11
ignore_index: 255
seed: 42
device: cuda
data_parallel: true
no_amp: false
flip_prob: 0.5
enable_random_crop: true
crop_width: 512
crop_height: 512
enable_rare_class_crop: true
rare_class_crop_prob: 0.8
rare_class_ids: [1, 2, 3, 5, 7, 8, 9, 10]
rare_class_min_pixels: 64
rare_class_min_ratio: 0.0005
rare_class_crop_attempts: 20
backbone_loader: auto
hf_dinov3_model_name_or_path: facebook/dinov3-vitl16-pretrain-lvd1689m
hf_local_files_only: true
mask2former_pretrained_model_name_or_path: facebook/mask2former-swin-large-ade-semantic
disable_mask2former_pretrained: false
freeze_backbone: false
hidden_dim: 256
m2f_no_object_weight: 0.1
m2f_class_weight: 2.0
m2f_mask_weight: 5.0
m2f_dice_weight: 5.0
m2f_train_num_points: 12544
m2f_oversample_ratio: 3.0
m2f_importance_sample_ratio: 0.75
classification_loss_type: ce
early_stopping_patience: 20
early_stopping_min_delta: 0.0001
enable_cls_aux: false
